//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: xml serialization ([XmlType]/[XmlElement]) enabled
    
// Generated from: client_config.proto
namespace NS_GAME.DATA
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBData_ClientSetting")]
  [global::System.Xml.Serialization.XmlType(TypeName=@"PBData_ClientSetting")]
  public partial class PBData_ClientSetting : global::ProtoBuf.IExtensible
  {
    public PBData_ClientSetting() {}
    
    // TYPE_MESSAGE.PBData_GameIDSettings : game_setting
    private PBData_GameIDSettings _game_setting;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"game_setting", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.Xml.Serialization.XmlElement(@"game_setting", Order = 1)]
        
    public PBData_GameIDSettings game_setting
    {
      get { return _game_setting; }
      set { _game_setting = value; }
    }
    // TYPE_MESSAGE.PBData_LoginSetting : login_setting
    private PBData_LoginSetting _login_setting;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"login_setting", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.Xml.Serialization.XmlElement(@"login_setting", Order = 2)]
        
    public PBData_LoginSetting login_setting
    {
      get { return _login_setting; }
      set { _login_setting = value; }
    }
    // TYPE_MESSAGE.PBData_LangSetting : lang_setting
    private PBData_LangSetting _lang_setting;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"lang_setting", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.Xml.Serialization.XmlElement(@"lang_setting", Order = 3)]
        
    public PBData_LangSetting lang_setting
    {
      get { return _lang_setting; }
      set { _lang_setting = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBData_GameIDSettings")]
  [global::System.Xml.Serialization.XmlType(TypeName=@"PBData_GameIDSettings")]
  public partial class PBData_GameIDSettings : global::ProtoBuf.IExtensible
  {
    public PBData_GameIDSettings() {}
    
    private uint _game_id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"game_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    [global::System.Xml.Serialization.XmlAttribute(@"game_id")]
        
    public uint game_id
    {
      get { return _game_id; }
      set { _game_id = value; }
    }
    private string _ad_id = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"ad_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    [global::System.Xml.Serialization.XmlAttribute(@"ad_id")]
        
    public string ad_id
    {
      get { return _ad_id; }
      set { _ad_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBData_LoginSetting")]
  [global::System.Xml.Serialization.XmlType(TypeName=@"PBData_LoginSetting")]
  public partial class PBData_LoginSetting : global::ProtoBuf.IExtensible
  {
    public PBData_LoginSetting() {}
    
    private string _login_url = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"login_url", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    [global::System.Xml.Serialization.XmlAttribute(@"login_url")]
        
    public string login_url
    {
      get { return _login_url; }
      set { _login_url = value; }
    }
    private string _update_url = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"update_url", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    [global::System.Xml.Serialization.XmlAttribute(@"update_url")]
        
    public string update_url
    {
      get { return _update_url; }
      set { _update_url = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBData_LangSetting")]
  [global::System.Xml.Serialization.XmlType(TypeName=@"PBData_LangSetting")]
  public partial class PBData_LangSetting : global::ProtoBuf.IExtensible
  {
    public PBData_LangSetting() {}
    
    private string _lang_type = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"lang_type", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    [global::System.Xml.Serialization.XmlAttribute(@"lang_type")]
        
    public string lang_type
    {
      get { return _lang_type; }
      set { _lang_type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}