//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: xml serialization ([XmlType]/[XmlElement]) enabled
    
// Generated from: resource_build.proto
namespace NS_GAME.DATA
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBData_EditorResourceInfoList")]
  [global::System.Xml.Serialization.XmlType(TypeName=@"PBData_EditorResourceInfoList")]
  public partial class PBData_EditorResourceInfoList : global::ProtoBuf.IExtensible
  {
    public PBData_EditorResourceInfoList() {}
    
    // TYPE_MESSAGE.PBData_EditorResourceInfo : resouce_list
    private  global::System.Collections.Generic.List<PBData_EditorResourceInfo> _resouce_list = new global::System.Collections.Generic.List<PBData_EditorResourceInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"resouce_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.Xml.Serialization.XmlElement(@"resouce_list", Order = 1)]
    
    public global::System.Collections.Generic.List<PBData_EditorResourceInfo> resouce_list
    {
      get { return _resouce_list; }
      set { _resouce_list = value; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBData_EditorResourceInfo")]
  [global::System.Xml.Serialization.XmlType(TypeName=@"PBData_EditorResourceInfo")]
  public partial class PBData_EditorResourceInfo : global::ProtoBuf.IExtensible
  {
    public PBData_EditorResourceInfo() {}
    
    private string _key = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"key", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    [global::System.Xml.Serialization.XmlAttribute(@"key")]
        
    public string key
    {
      get { return _key; }
      set { _key = value; }
    }
    private string _path = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"path", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    [global::System.Xml.Serialization.XmlAttribute(@"path")]
        
    public string path
    {
      get { return _path; }
      set { _path = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBData_AssetResourceInfo")]
  [global::System.Xml.Serialization.XmlType(TypeName=@"PBData_AssetResourceInfo")]
  public partial class PBData_AssetResourceInfo : global::ProtoBuf.IExtensible
  {
    public PBData_AssetResourceInfo() {}
    
    private string _key = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"key", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    [global::System.Xml.Serialization.XmlAttribute(@"key")]
        
    public string key
    {
      get { return _key; }
      set { _key = value; }
    }
    private string _path = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"path", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    [global::System.Xml.Serialization.XmlAttribute(@"path")]
        
    public string path
    {
      get { return _path; }
      set { _path = value; }
    }
    private PBData_AssetResourceInfo _dependence_list = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"dependence_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    [global::System.Xml.Serialization.XmlElement(@"dependence_list", Order = 3)]
        
    public PBData_AssetResourceInfo dependence_list
    {
      get { return _dependence_list; }
      set { _dependence_list = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBData_AssetResourceInfoList")]
  [global::System.Xml.Serialization.XmlType(TypeName=@"PBData_AssetResourceInfoList")]
  public partial class PBData_AssetResourceInfoList : global::ProtoBuf.IExtensible
  {
    public PBData_AssetResourceInfoList() {}
    
    // TYPE_MESSAGE.PBData_AssetObjectResourceInfo : object_list
    private  global::System.Collections.Generic.List<PBData_AssetObjectResourceInfo> _object_list = new global::System.Collections.Generic.List<PBData_AssetObjectResourceInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"object_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.Xml.Serialization.XmlElement(@"object_list", Order = 1)]
    
    public global::System.Collections.Generic.List<PBData_AssetObjectResourceInfo> object_list
    {
      get { return _object_list; }
      set { _object_list = value; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBData_AssetObjectResourceInfo")]
  [global::System.Xml.Serialization.XmlType(TypeName=@"PBData_AssetObjectResourceInfo")]
  public partial class PBData_AssetObjectResourceInfo : global::ProtoBuf.IExtensible
  {
    public PBData_AssetObjectResourceInfo() {}
    
    private string _key = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"key", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    [global::System.Xml.Serialization.XmlAttribute(@"key")]
        
    public string key
    {
      get { return _key; }
      set { _key = value; }
    }
    private PBData_AssetResourceInfo _mesh = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"mesh", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    [global::System.Xml.Serialization.XmlElement(@"mesh", Order = 2)]
        
    public PBData_AssetResourceInfo mesh
    {
      get { return _mesh; }
      set { _mesh = value; }
    }
    private PBData_AssetResourceInfo _bone = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"bone", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    [global::System.Xml.Serialization.XmlElement(@"bone", Order = 3)]
        
    public PBData_AssetResourceInfo bone
    {
      get { return _bone; }
      set { _bone = value; }
    }
    // TYPE_MESSAGE.PBData_AssetResourceInfo : materials
    private  global::System.Collections.Generic.List<PBData_AssetResourceInfo> _materials = new global::System.Collections.Generic.List<PBData_AssetResourceInfo>();
    [global::ProtoBuf.ProtoMember(4, Name=@"materials", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.Xml.Serialization.XmlElement(@"materials", Order = 4)]
    
    public global::System.Collections.Generic.List<PBData_AssetResourceInfo> materials
    {
      get { return _materials; }
      set { _materials = value; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBData_ResourceConfigTree")]
  [global::System.Xml.Serialization.XmlType(TypeName=@"PBData_ResourceConfigTree")]
  public partial class PBData_ResourceConfigTree : global::ProtoBuf.IExtensible
  {
    public PBData_ResourceConfigTree() {}
    
    private string _version_id = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"version_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    [global::System.Xml.Serialization.XmlAttribute(@"version_id")]
        
    public string version_id
    {
      get { return _version_id; }
      set { _version_id = value; }
    }
    // TYPE_MESSAGE.PBData_ResourceConfigInfo : config_list
    private  global::System.Collections.Generic.List<PBData_ResourceConfigInfo> _config_list = new global::System.Collections.Generic.List<PBData_ResourceConfigInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"config_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.Xml.Serialization.XmlElement(@"config_list", Order = 2)]
    
    public global::System.Collections.Generic.List<PBData_ResourceConfigInfo> config_list
    {
      get { return _config_list; }
      set { _config_list = value; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBData_ResourceConfigInfo")]
  [global::System.Xml.Serialization.XmlType(TypeName=@"PBData_ResourceConfigInfo")]
  public partial class PBData_ResourceConfigInfo : global::ProtoBuf.IExtensible
  {
    public PBData_ResourceConfigInfo() {}
    
    private string _key = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"key", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    [global::System.Xml.Serialization.XmlAttribute(@"key")]
        
    public string key
    {
      get { return _key; }
      set { _key = value; }
    }
    private string _path = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"path", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    [global::System.Xml.Serialization.XmlAttribute(@"path")]
        
    public string path
    {
      get { return _path; }
      set { _path = value; }
    }
    private string _version_id = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"version_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    [global::System.Xml.Serialization.XmlAttribute(@"version_id")]
        
    public string version_id
    {
      get { return _version_id; }
      set { _version_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"TGameResourceType")]
    [global::System.Xml.Serialization.XmlType(TypeName=@"TGameResourceType")]
    public enum TGameResourceType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"enText", Value=1)]
      [global::System.Xml.Serialization.XmlEnum(@"enText")]
      enText = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"enUI", Value=2)]
      [global::System.Xml.Serialization.XmlEnum(@"enUI")]
      enUI = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"enScene", Value=3)]
      [global::System.Xml.Serialization.XmlEnum(@"enScene")]
      enScene = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"enFX", Value=4)]
      [global::System.Xml.Serialization.XmlEnum(@"enFX")]
      enFX = 4
    }
  
}